# Generated by Django 5.0.2 on 2024-08-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rename_autores_livro_autor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="autor",
            field=models.ManyToManyField(blank=True, related_name="livros", to="core.autor"),
        ),
    ]
