# Generated by Django 4.2.16 on 2024-09-27 19:16

import core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_itenscompra"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.user.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="passage_id",
            field=models.CharField(default=123456, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
